version: '3.8'
services:
  web:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: always
    env_file:
      - ../.env
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
